### ISSUE TITLE
User,Offlineが扱いづらい

### ISSUE THREAD

**Issue by HRSNOZOMU** [YNU17-IEEP-GroupG/Reversi#3]
今のところCPU戦画面等は配列でループ処理してるので,難易度別に戦績取得のメソッドがある状態だと非効率すぎる。
適当に添え字を決めて配列化できないか？

**Comment by yuta-takanashi** [comment]
@HRSNOZOMU 
13c38b2e8ee957f62e42621cb6b89a228c645e49
こんな感じにしたけど、気に入らなかったら変えちゃって
